### ISSUE TITLE
Rename App.Run and App.RunArgs to App.Parse and App.ParseArgs

### ISSUE THREAD

**Issue by ibraimgm** [ibraimgm/libcmd#2]
In `app.go`, the `App` struct (that has a `Cmd` embedded) has a `Run` method that obfuscates the meaning of the original `Cmd.Run` method. This makes the registration of a run callback directly on `App` a bit clunky, since the user must write `App.Cmd.Run`.

The idea is to rename `App.Run` to `App.Parse`. To keep the API consistent, `App.RunArgs` must also be renamed to `App.ParseArgs`.

Note that all test cases must also be changed to use the new name.

**Comment by David373** [comment]
I'll do it! :)

**Comment by ibraimgm** [comment]
Fixed by #3
